export const LAST_TEN_HADITHS = [
  {
    id: 1,
    tag: 'Qur\'on',
    arabic: 'إِنَّا أَنْزَلْنَاهُ فِي لَيْلَةِ الْقَدْرِ',
    uzbek: "Biz uni Qadr kechasida nozil qildik.",
    source: "Qur'on 97:1",
  },
  {
    id: 2,
    tag: 'Qur\'on',
    arabic: 'لَيْلَةُ الْقَدْرِ خَيْرٌ مِنْ أَلْفِ شَهْرٍ',
    uzbek: 'Qadr kechasi ming oydan yaxshiroqdir.',
    source: "Qur'on 97:3",
  },
  {
    id: 3,
    tag: 'Qur\'on',
    arabic: 'إِنَّا أَنْزَلْنَاهُ فِي لَيْلَةٍ مُبَارَكَةٍ',
    uzbek: 'Biz uni muborak kechada nozil qildik.',
    source: "Qur'on 44:3",
  },
  {
    id: 4,
    tag: 'Qadr',
    arabic: 'تَحَرَّوْا لَيْلَةَ الْقَدْرِ فِي الْوِتْرِ مِنَ الْعَشْرِ الأَوَاخِرِ',
    uzbek: "Qadr kechasini oxirgi o'nlikning toq kechalarida qidiring.",
    source: 'Sahih al-Bukhari 2017',
  },
  {
    id: 5,
    tag: 'Qiyom',
    arabic: 'مَنْ قَامَ لَيْلَةَ الْقَدْرِ إِيمَانًا وَاحْتِسَابًا غُفِرَ لَهُ',
    uzbek: "Kim Qadr kechasini imon va savob umidida qiyom bilan o'tkazsa, gunohlari kechiriladi.",
    source: 'Sahih al-Bukhari 2014',
  },
  {
    id: 6,
    tag: 'Oxirgi 10',
    arabic: 'إِذَا دَخَلَ الْعَشْرُ شَدَّ مِئْزَرَهُ وَأَحْيَا لَيْلَهُ وَأَيْقَظَ أَهْلَهُ',
    uzbek: "Oxirgi o'n kun kirganda Rasululloh ibodatni kuchaytirar, kechani tiriltirar va ahllarini uyg'otardilar.",
    source: 'Sahih al-Bukhari 2024, Sahih Muslim 1174',
  },
  {
    id: 7,
    tag: 'Imom bilan namoz',
    arabic: 'مَنْ قَامَ مَعَ الإِمَامِ حَتَّى يَنْصَرِفَ كُتِبَ لَهُ قِيَامُ لَيْلَةٍ',
    uzbek: 'Kim imom bilan namozni oxirigacha o\'qisa, unga bir kecha qiyom savobi yoziladi.',
    source: 'Jami at-Tirmidhi 806',
  },
  {
    id: 8,
    tag: 'Duo',
    arabic: 'اللَّهُمَّ إِنَّكَ عَفُوٌّ تُحِبُّ الْعَفْوَ فَاعْفُ عَنِّي',
    uzbek: "Qadr kechasida aytiladigan eng mashhur duo: Allohim, Sen afv etuvchisan, afvni yaxshi ko'rasan, meni afv et.",
    source: 'Sunan Ibn Majah 3850',
  },
  {
    id: 9,
    tag: 'I\'tikof',
    arabic: 'كَانَ يَعْتَكِفُ فِي الْعَشْرِ الأَوَاخِرِ مِنْ رَمَضَانَ',
    uzbek: "Rasululloh Ramazonning oxirgi o'n kunida i'tikof qilardilar.",
    source: 'Sahih al-Bukhari 2025',
  },
  {
    id: 10,
    tag: 'Adab',
    arabic: 'خَرَجْتُ لأُخْبِرَكُمْ بِلَيْلَةِ الْقَدْرِ فَتَلَاحَى فُلاَنٌ وَفُلاَنٌ',
    uzbek: "Ixtilof sabab Qadr kechasining aniq vaqti bildirilmay qoldi; bahs va tortishuvdan uzoq bo'lish kerak.",
    source: 'Sahih al-Bukhari 2023',
  },
];
