export const NAFS_STAGE_EVIDENCE = {
  1: [
    {
      id: 'ammora-yusuf-53',
      type: "Qur'on",
      title: "Nafsning asosiy xavfi",
      summary: "Nafs o'zi bilan qolsa yomonlikka tortadi. Najot Allohning rahmati va doimiy nazoratda.",
      reference: 'Yusuf 12:53',
      url: 'https://quran.com/12/53',
    },
    {
      id: 'ammora-shams-9',
      type: "Qur'on",
      title: 'Poklash va pasayish mezoni',
      summary: "Kim nafsini poklasa najot topadi, kim iflos qilsa ziyon ko'radi.",
      reference: 'Shams 91:9-10',
      url: 'https://quran.com/en/ash-shams/7-10',
    },
    {
      id: 'ammora-tirmidhi-1621',
      type: 'Hadis',
      title: 'Ichki jihod ta\'rifi',
      summary: "Haqiqiy mujohid nafsiga qarshi Alloh itoatida kurashadigan kishidir.",
      reference: 'Jami at-Tirmidhi 1621',
      grade: 'Hasan (Tirmidhi) | Sahih (Ibn Hibban)',
      gradeTone: 'hasan',
      url: 'https://sunnah.com/tirmidhi:1621',
    },
  ],
  2: [
    {
      id: 'lavvoma-qiyamah-2',
      type: "Qur'on",
      title: 'Malomat qiluvchi nafs',
      summary: "Lavvoma bosqichining belgisi: inson xatodan keyin o'zini oqlamaydi, o'zini hisob qiladi va qaytishga jur'at topadi.",
      reference: 'Qiyamah 75:2',
      url: 'https://legacy.quran.com/75/2',
    },
    {
      id: 'lavvoma-bukhari-6116',
      type: 'Hadis',
      title: "G'azabda birinchi tavsiya",
      summary: "Lavvoma uchun birinchi intizom: g'azab paytida nafsga emas, sunnatga ergashish - javobni ushlab qolish.",
      reference: 'Sahih al-Bukhari 6116',
      grade: 'Sahih',
      gradeTone: 'sahih',
      url: 'https://sunnah.com/bukhari:6116',
    },
    {
      id: 'lavvoma-muslim-2609',
      type: 'Hadis',
      title: 'Kuch mezoni',
      summary: "Haqiqiy kuch - bahsda yutish emas, nafs qaynaganda ham qalb adabini yo'qotmaslikdir.",
      reference: 'Sahih Muslim 2609a',
      grade: 'Sahih',
      gradeTone: 'sahih',
      url: 'https://sunnah.com/muslim:2609a',
    },
  ],
  3: [
    {
      id: 'mulhima-shams-8',
      type: "Qur'on",
      title: 'Fujur va taqvo ilhomi',
      summary: 'Nafsga yomonlik va taqvo yo\'li bildirildi: tanlovga javobgarlik bor.',
      reference: 'Shams 91:8',
      url: 'https://quran.com/en/ash-shams/7-10',
    },
    {
      id: 'mulhima-aajurri',
      type: 'Ulama',
      title: "Intizomning manbasi",
      summary: "Nafs tarbiyasining dalili Qur'on, Sunnat va ulamolar yo'riqlarida yotadi.",
      reference: 'Imom al-Ajurri, Adab an-Nufus',
      url: 'https://islamqa.info/en/answers/178627',
    },
  ],
  4: [
    {
      id: 'mutmainna-rad-28',
      type: "Qur'on",
      title: 'Qalb taskini',
      summary: "Qalbning haqiqiy sokinligi zikr bilan bo'ladi; bu bosqichning markazi shu.",
      reference: "Ra'd 13:28",
      url: 'https://quran.com/13/28',
    },
    {
      id: 'mutmainna-fajr-27',
      type: "Qur'on",
      title: 'Tranquil nafs chaqiruvi',
      summary: "Mutma'inna nafs Alloh huzuriga xotirjam holda qaytishga tayyor bo'ladi.",
      reference: 'Fajr 89:27',
      url: 'https://legacy.quran.com/89/27',
    },
  ],
  5: [
    {
      id: 'roziya-fajr-28',
      type: "Qur'on",
      title: "Rozi bo'lish maqomi",
      summary: "Bandaning qalbi taqdirga rozi bo'lsa, yo'li barqaror bo'lib boradi.",
      reference: 'Fajr 89:28',
      url: 'https://quran.com/en/al-fajr/28',
    },
    {
      id: 'roziya-yaqeen-tazkiyah',
      type: 'Maqola',
      title: 'Tazkiya usullari',
      summary: "Muraqaba, tavba, yaxshi amal va axloqni tuzatish birgalikda nafsi tarbiyalaydi.",
      reference: 'Yaqeen Institute',
      url: 'https://yaqeeninstitute.org/what-islam-says-about/islam-and-mental-health-and-wellness',
    },
  ],
  6: [
    {
      id: 'marziya-fajr-28',
      type: "Qur'on",
      title: 'Rozi va rozi qilingan holat',
      summary: "Banda Allohdan rozi, Alloh ham bandadan rozi bo'ladigan holatga intiladi.",
      reference: 'Fajr 89:28',
      url: 'https://quran.com/en/al-fajr/28',
    },
    {
      id: 'marziya-muslim-8a',
      type: 'Hadis',
      title: 'Ihsan standarti',
      summary: "Ihsan: Allohni ko'rib turgandek ibodat qilish; ko'rmasang ham U seni ko'radi.",
      reference: 'Sahih Muslim 8a',
      grade: 'Sahih',
      gradeTone: 'sahih',
      url: 'https://sunnah.com/muslim:8a',
    },
  ],
  7: [
    {
      id: 'sofiya-fajr-29',
      type: "Qur'on",
      title: 'Oxirgi chaqiriq',
      summary: "Poklangan nafs uchun nihoyat: solih bandalar safiga kirish va Jannatga da'vat.",
      reference: 'Fajr 89:29-30',
      url: 'https://quran.com/en/al-fajr/27-30',
    },
    {
      id: 'sofiya-fotir-18',
      type: "Qur'on",
      title: "Shaxsiy mas'uliyat",
      summary: "Har jon o'z yukini ko'taradi; poklanishning foydasi avvalo insonning o'ziga qaytadi.",
      reference: 'Fotir 35:18',
      url: 'https://quran.com/35/18',
    },
    {
      id: 'sofiya-ghazali-book',
      type: 'Kitob',
      title: "Nafsni jilovlash bo'yicha klassik manba",
      summary: "Ihyo kitoblari XXII-XXIII nafs tarbiyasi va shahvatni sindirishga bag'ishlangan.",
      reference: "Al-G'azzoliy, Ihya' Ulum ad-Din",
      url: 'https://openlibrary.org/books/OL4018725M/On_disciplining_the_soul',
    },
  ],
};

export const ULAMA_NASIHA = [
  {
    id: 'aajurri-evidence',
    scholar: 'Imom al-Ajurri',
    work: 'Adab an-Nufus',
    advice: "Nafs tarbiyasi Qur'on, Sunnat va ilm asosida bo'lishi kerak.",
    action: "Har bir bosqichga kamida 1 dalil yozib boring va amaliyotni dalil bilan bog'lang.",
    source: 'https://islamqa.info/en/answers/178627',
  },
  {
    id: 'ibn-qayyim-mujahid',
    scholar: 'Ibn al-Qayyim (naql sharhi orqali)',
    work: 'Mujohada an-nafs mavzusi',
    advice: "Nafsga qarshi kurash bir martalik emas, doimiy intizomli jarayon.",
    action: "Har kuni bitta qarshi-amal tanlang: nafs istaganini kechiktiring yoki me'yorlang.",
    source: 'https://islamqa.info/en/answers/202449',
  },
  {
    id: 'ghazali-riyada',
    scholar: "Imom al-G'azzoliy",
    work: "Ihya' Ulum ad-Din (XXII-XXIII)",
    advice: "Qalb kasalliklari davosi muntazam muhasaba va shahvatni boshqarish bilan keladi.",
    action: "Haftasiga 1 marta xulosa yozing: qaysi odat qalbni og'irlashtiryapti?",
    source: 'https://openlibrary.org/books/OL4018725M/On_disciplining_the_soul',
  },
];

export const NAFS_ARTICLE_LIBRARY = [
  {
    id: 'article-islamqa-discipline',
    title: "Nafsni intizomga solish: fiqhiy yondashuv",
    publisher: 'IslamQA',
    tag: 'Fiqh + Tarbiya',
    stageIds: [1, 2],
    summaryUz: "Nafs tarbiyasi hissiyotga emas, dalilga asoslanadi: Qur'on, Sunnat va muntazam muhasaba birga yurishi kerak.",
    paragraphsUz: [
      "Maqola markaziy g'oya sifatida shuni beradi: nafsni sindirish degani tanani qiynash emas, balki haromdan to'xtash va halolga intizom kiritishdir.",
      "Ushbu yondashuvda uch ustun bor: ilm, amal va sabr. Ilmsiz amal beqaror bo'ladi, amalsiz ilm esa nafsni to'xtatmaydi.",
      "Kunlik amaliyotda kichik, lekin takrorlanuvchi qadamlar eng samarali: niyatni yangilash, xatodan keyin tez tavba, odatlarni me'yorlash.",
    ],
    actionPlan: [
      "Har kuni bitta nafsiy zaif nuqtani yozing.",
      "Shu nuqta uchun bitta qarshi-amal belgilang.",
      "Kechqurun 3 daqiqalik muhasaba bilan natijani qayd qiling.",
    ],
    sourceLabel: 'IslamQA #178627',
  },
  {
    id: 'article-islamqa-mujahid',
    title: '"Mujohid nafsiga qarshi kurashadi" hadisi sharhi',
    publisher: 'IslamQA',
    tag: 'Hadis tahlili',
    stageIds: [2, 3],
    summaryUz: "Lavvoma bosqichi uchun asosiy xulosa: kuch - bahsda emas, gunohga eltuvchi impulsni to'xtata olishdadir.",
    paragraphsUz: [
      "Matnda mujohada bir martalik his emasligi aytiladi: qalbdagi pushaymonlik har kuni amaliy odatga aylanganda Lavvoma kuchayadi.",
      "Nafs bilan kurashning eng amaliy yo'li - impuls paytida to'xtash, o'zini oqlashni bas qilish va qarorni dalil asosida olish.",
      "Qattiq vaziyatlarda kichik qadamlar ishlaydi: javobni kechiktirish, zikr, tahorat, keyin tinch va adolatli gaplashish.",
    ],
    actionPlan: [
      "G'azabda darhol javob bermaslik qoidasi qo'ying.",
      "2 daqiqalik sukut + zikr protokolini ishga tushiring.",
      "Kun oxirida qaysi holatda o'zingizni boshqarganingizni yozing.",
    ],
    sourceLabel: 'IslamQA #202449',
  },
  {
    id: 'article-yaqeen-tazkiyah',
    title: 'Tazkiya asoslari: muraqaba, tavba va axloq',
    publisher: 'Yaqeen Institute',
    tag: 'Amaliy metod',
    stageIds: [3, 4, 5],
    summaryUz: "Tazkiya qalb, fikr va odatni bir vaqtda tozalash jarayoni ekanini amaliy tilda tushuntiradi.",
    paragraphsUz: [
      "Muraqaba - Alloh nazoratini qalbda jonli ushlash; bu his nafsiy impulslarni erta bosqichda to'xtatishga yordam beradi.",
      "Tavba faqat xatodan keyingi pushaymonlik emas, balki takror xatoni kamaytiradigan reja bilan birga bo'lishi kerak.",
      "Maqolada yaxshi axloqni ichki poklanishning natijasi sifatida ko'rsatadi: qalb tozalansa, muomala ham tozalanadi.",
    ],
    actionPlan: [
      "Tongda 1 daqiqa niyat-muraqaba qiling.",
      "Har xatodan keyin 'nima o'zgartiraman?' savoliga yozma javob bering.",
      "Haftasiga 1 marta bitta axloqiy sifatni yaxshilash rejasini tuzing.",
    ],
    sourceLabel: 'Yaqeen Institute (Tazkiya mavzusi)',
  },
  {
    id: 'article-nafs-states',
    title: 'Nafs holatlari: Ammora, Lavvoma, Mutma\'inna',
    publisher: 'IslamQA.org (SeekersGuidance riwayati)',
    tag: 'Nazariy asos',
    stageIds: [1, 2, 4],
    summaryUz: "Nafs bosqichlari qat'iy yorliq emas, balki insondagi holatlarning dinamik o'zgarishini ko'rsatadi.",
    paragraphsUz: [
      "Ammora holatida inson xohishga tez ergashadi. Lavvoma bosqichida vijdon uyg'onib, o'zini hisob qilish boshlanadi.",
      "Mutma'inna holati zohiriy tinchlik emas, balki zikr va itoat orqali ichki barqarorlik topishdir.",
      "Maqola bosqichlar oralig'idagi o'tishning kaliti sifatida muntazam muhasaba va kichik-intizomiy odatlarni beradi.",
    ],
    actionPlan: [
      "Har haftada o'zingizni qaysi holatga yaqin deb baholang.",
      "Bahoga qarab keyingi 7 kunlik bitta odat tanlang.",
      "Progressni checklist orqali o'lchang.",
    ],
    sourceLabel: 'IslamQA.org / SeekersGuidance sharhi',
  },
  {
    id: 'article-ghazali-translation',
    title: "Ihyo XXII-XXIII: nafsni tarbiya qilish",
    publisher: 'Open Library',
    tag: 'Klassik manba',
    stageIds: [5, 6, 7],
    summaryUz: "Imom G'azzoliy nafs tarbiyasini qalb kasalliklarini aniqlash va davolash tizimi sifatida bayon qiladi.",
    paragraphsUz: [
      "Asarda shahvat, g'azab, kibr, hasad kabi ichki illatlar tashqi gunohlardan oldin qalbda shakllanishi tushuntiriladi.",
      "Davolash usuli ikki yo'nalishda beriladi: zararli odatlarni to'xtatish va o'rniga foydali odatlarni bosqichma-bosqich kiritish.",
      "Muhasaba va riyozatning maqsadi o'zini qiynash emas, nafsni boshqariladigan holatga olib kelishdir.",
    ],
    actionPlan: [
      "Bir oy davomida bitta ichki illatni tanlab ishlang.",
      "Unga qarshi 2 ta amaliy odat yozing.",
      "Har juma natijani qayta tahlil qiling.",
    ],
    sourceLabel: "Ihyo' Ulum ad-Din, XXII-XXIII boblar",
  },
];

export const ANGER_SOS_STEPS = [
  {
    id: 'pause-breath',
    title: "30 soniya to'xtash",
    detail: "Gapirishni to'xtating, 4-4 ritmda 5 marta chuqur nafas oling.",
  },
  {
    id: 'istiadha',
    title: "Isti'oza va zikr",
    detail: "A'uzu billahi minash-shaytanir rajim deb, ovozni pasaytiring.",
  },
  {
    id: 'switch-posture',
    title: "Holatni o'zgartirish",
    detail: "Turgan bo'lsangiz o'tiring, o'tirgan bo'lsangiz yoting yoki joyni tark eting.",
  },
  {
    id: 'wudu-delay',
    title: "Tahorat va kechiktirilgan javob",
    detail: "Imkon bo'lsa tahorat qiling, javobni kamida 2 daqiqa kechiktiring.",
  },
];
