// Shayx Muhammad Sodiq Muhammad Yusuf darsliklari
// Video IDlarni YouTube dan oling: youtube.com/watch?v=VIDEO_ID

export const VIDEO_CATEGORIES = [
  {
    id: 'ramazon',
    label: 'Ramazon darsliklari',
    icon: '🌙',
    color: '#16A34A',
  },
  {
    id: 'ruhiy',
    label: 'Ruhiy tarbiya',
    icon: '🫀',
    color: '#7C3AED',
  },
];

export const LECTURES = [
  // === RAMAZON ===
  {
    id: 'r001',
    categoryId: 'ramazon',
    title: '01. Кибр ва унинг турлари | Kibr va uning turlari',
    duration: '7:04',
    videoId: 'Pcwxwl6geAY',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r002',
    categoryId: 'ramazon',
    title: '02. Кибрнинг даражалари | Kibrning darajalari',
    duration: '7:42',
    videoId: 'Iudhed1r2XA',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r003',
    categoryId: 'ramazon',
    title: '03. Кибр ҳақидаги ҳадислар | Kibr haqidagi hadislar',
    duration: '4:30',
    videoId: 'k4i6py1OTQU',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r004',
    categoryId: 'ramazon',
    title: '04. Кибрнинг давоси | Kibrning davosi',
    duration: '3:20',
    videoId: 'TtDCOMHE6Y8',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r005',
    categoryId: 'ramazon',
    title: '05. Насаб билан кибрланиш | Nasab bilan kibrlanish',
    duration: '2:55',
    videoId: 'dklXHjpMRoU',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r006',
    categoryId: 'ramazon',
    title: '06. Гўзаллик ва мол дунё билан кибрланиш | Go\'zallik va mol dunyo bilan kibrlanish',
    duration: '4:29',
    videoId: 'Fp97CvVZ4LY',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r007',
    categoryId: 'ramazon',
    title: '07. Салафи солиҳларнинг мутавозеликлари | Salafi solihlarning mutavozeliklari',
    duration: '4:48',
    videoId: 'UYw3V9YIb-8',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r008',
    categoryId: 'ramazon',
    title: '08. Манманлик ҳақида | Manmanlik haqida',
    duration: '3:58',
    videoId: 'wHINVqbAnV4',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r009',
    categoryId: 'ramazon',
    title: '09. Қоруннинг манманлиги | Qorunning manmanligi',
    duration: '4:41',
    videoId: 'J5EZ361cWXc',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r010',
    categoryId: 'ramazon',
    title: '10. Ҳунайн кунидаги Аллоҳнинг нусрати | Hunayn kunidagi Allohning nusrati',
    duration: '6:02',
    videoId: '9BllD58orsI',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r011',
    categoryId: 'ramazon',
    title: '11. Манманлик ҳақидаги ҳадис | Manmanlik haqidagi hadis',
    duration: '1:37',
    videoId: 'yPIFqelPHY8',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r012',
    categoryId: 'ramazon',
    title: '12. Манманликнинг сабаблари | Manmanlikning sabablari',
    duration: '7:49',
    videoId: 'Kuf4C5RgmpE',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r013',
    categoryId: 'ramazon',
    title: '13. Бахиллик ҳақида | Baxillik haqida',
    duration: '5:52',
    videoId: 'CjHEKJu8SS4',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r014',
    categoryId: 'ramazon',
    title: '14. Бахилликнинг оқибатлари | Baxillikning oqibatlari',
    duration: '5:46',
    videoId: 'ed5snhFGYs4',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r015',
    categoryId: 'ramazon',
    title: '15. Барча мулк Аллоҳникидир | Barcha mulk Allohnikidir',
    duration: '3:11',
    videoId: 'ZR1QgWZCe9w',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r016',
    categoryId: 'ramazon',
    title: '16. Ўзига бахиллик қилувчи киши | O\'ziga baxillik qiluvchi kishi',
    duration: '1:20',
    videoId: 'rHvGW-ncF9A',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r017',
    categoryId: 'ramazon',
    title: '17. Мўмин киши бахил бўлмайди | Mo\'min kishi baxil bo\'lmaydi',
    duration: '2:09',
    videoId: 'vGHjMNKKz7I',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r018',
    categoryId: 'ramazon',
    title: '18. Бахилликнинг давоси | Baxillikning davosi',
    duration: '3:21',
    videoId: 'smRuLKNTeyY',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r019',
    categoryId: 'ramazon',
    title: '19. Тасвирга олиш одоблари | Tasvirga olish odoblari',
    duration: '6:13',
    videoId: 'mMXJUJHE2f8',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r020',
    categoryId: 'ramazon',
    title: '20. Мўмин мусулмон кишининг мол дунёга муносабати | Mo\'min musulmon kishining mol dunyoga munosabati',
    duration: '3:07',
    videoId: 'siDDQRiD07A',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r021',
    categoryId: 'ramazon',
    title: '21. Дирҳам - чаёндир! | Dirham - chayondir!',
    duration: '1:35',
    videoId: 'pdoNTUMlnr0',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r022',
    categoryId: 'ramazon',
    title: '22. Ҳалол мол дунё топиш ҳар бир мусулмоннинг бурчидир',
    duration: '5:11',
    videoId: '_HWflFQ7BvY',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r023',
    categoryId: 'ramazon',
    title: '23. Солиҳ банданинг қўлидаги солиҳ мол | Solih bandaning qo\'lidagi solih mol',
    duration: '1:50',
    videoId: 'gHILFarfwcU',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r024',
    categoryId: 'ramazon',
    title: '24. Молни беҳуда сарф қилмаслик | Molni behuda sarf qilmaslik',
    duration: '2:33',
    videoId: '88VjILhPCj8',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r025',
    categoryId: 'ramazon',
    title: '25. Мол-дунёнинг диний фойдаси | Mol-dunyoning diniy foydasi',
    duration: '8:29',
    videoId: '5cILzZHdre4',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r026',
    categoryId: 'ramazon',
    title: '26. Мол-дунёнинг зарарлари | Mol-dunyoning zararlari',
    duration: '6:39',
    videoId: '37IEN1fWwtM',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r027',
    categoryId: 'ramazon',
    title: '27. Тақводорлик китоби | Taqvodorlik kitobi',
    duration: '2:57',
    videoId: '5FScOfbmRS8',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r028',
    categoryId: 'ramazon',
    title: '28. Телефондан фойдаланиш одоблари | Telefondan foydalanish odoblari',
    duration: '8:01',
    videoId: 'wUInjtxfAmk',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r029',
    categoryId: 'ramazon',
    title: '29. Тамагирлик ҳақида | Tamagirlik haqida',
    duration: '5:01',
    videoId: 'yuv3ZPeBtfI',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r030',
    categoryId: 'ramazon',
    title: '30. Бойлик - молнинг кўплигида эмас',
    duration: '2:41',
    videoId: 'Dcu8JFjTers',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r031',
    categoryId: 'ramazon',
    title: '31. Олимлар кимлар | Olimlar kimlar',
    duration: '2:41',
    videoId: 'KVDFoJH78ys',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r032',
    categoryId: 'ramazon',
    title: '32. Икки оч бўри | Ikki och bo\'ri',
    duration: '1:04',
    videoId: '_f-dTfUgsj4',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r033',
    categoryId: 'ramazon',
    title: '33. Тамагирликнинг давоси | Tamagirlikning davosi',
    duration: '1:59',
    videoId: 'BBwVJtyzR8Y',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r034',
    categoryId: 'ramazon',
    title: '34. Иқтисод - пайғамбарликнинг 25 дан 1 қисмидир',
    duration: '2:15',
    videoId: 'VBDJiDnbJa0',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r035',
    categoryId: 'ramazon',
    title: '35. Аллоҳдан беҳожатликни сўрашлик | Allohdan behojatlikni so\'rashlik',
    duration: '2:27',
    videoId: 'hU4ORFT3sVs',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r036',
    categoryId: 'ramazon',
    title: '36. Ҳамманинг ризқи белгилаб қўйилган | Hammaning rizqi belgilab qo\'yilgan',
    duration: '3:21',
    videoId: 'xMtPwS6Ytgw',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r037',
    categoryId: 'ramazon',
    title: '37. Аллоҳ ажойиб тарзда ризқ беради | Alloh ajoyib tarzda rizq beradi',
    duration: '4:08',
    videoId: '-_PSsrvsm7Q',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r038',
    categoryId: 'ramazon',
    title: '38. Қаноатли бўлиш ҳақида | Qanoatli bo\'lish haqida',
    duration: '3:21',
    videoId: 'TLfzCa22phM',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r039',
    categoryId: 'ramazon',
    title: '39. Тамагирликнинг оқибатлари | Tamagirlikning oqibatlari',
    duration: '2:20',
    videoId: '1MXZ37KiEnE',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r040',
    categoryId: 'ramazon',
    title: '40. Ғурурга кетиш ҳақида | G\'ururga ketish haqida',
    duration: '3:30',
    videoId: 'jupsxA1opnE',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r041',
    categoryId: 'ramazon',
    title: '41. Ғурурга кетиш оғир ҳасталик | G\'ururga ketish og\'ir hastalik',
    duration: '7:46',
    videoId: 'N1iqYVcu2dc',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r042',
    categoryId: 'ramazon',
    title: '42. Аллоҳнинг ваъдаси ҳақдир | Allohning va\'dasi haqdir',
    duration: '5:29',
    videoId: 'orVDWtiqrdg',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r043',
    categoryId: 'ramazon',
    title: '43. Динсизларнинг ғурурга кетиши | Dinsizlarning g\'ururga ketishi',
    duration: '3:57',
    videoId: 'SOYJI2wF_bc',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r044',
    categoryId: 'ramazon',
    title: '44. Осийларнинг ғурурга кетиши | Osiylarning g\'ururga ketishi',
    duration: '3:03',
    videoId: 'ccGvD7Cc1sM',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r045',
    categoryId: 'ramazon',
    title: '45. Илм ва ибодат билан ғурурга кетиш | Ilm va ibodat bilan g\'ururga ketish',
    duration: '6:23',
    videoId: 'BgkvdJL4Z3k',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r046',
    categoryId: 'ramazon',
    title: '46. Илмига амал қиладиган аммо аҳлоқсиз кишнинг ғурурга кетиши',
    duration: '2:42',
    videoId: 'KQC4Vodj1l0',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r047',
    categoryId: 'ramazon',
    title: '47. Обидларнинг ғурурга кетиши | Obidlarning g\'ururga ketishi',
    duration: '4:41',
    videoId: '-1GnA1s5nxw',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r048',
    categoryId: 'ramazon',
    title: '48. Воизларнинг ғурурга кетиши | Voizlarning g\'ururga ketishi',
    duration: '2:23',
    videoId: 'd1F2b8oIdbo',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r049',
    categoryId: 'ramazon',
    title: '49. Тасаввуфни даъво қилувчиларнинг ғурурга кетиши',
    duration: '2:56',
    videoId: 'wqjV_qFEVxY',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r050',
    categoryId: 'ramazon',
    title: '50. Ғурурга кетишнинг давоси | G\'ururga ketishning davosi',
    duration: '2:39',
    videoId: 'vVOO0SrGqno',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r051',
    categoryId: 'ramazon',
    title: '19. Аллоҳга таваккал | Allohga tavakkal',
    duration: '1:27',
    videoId: 'EjxqfUaM6GM',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r052',
    categoryId: 'ramazon',
    title: '51. Ғазаб ҳақида | G\'azab haqida',
    duration: '3:44',
    videoId: 'viQo8KxKINA',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r053',
    categoryId: 'ramazon',
    title: '52. Ғазабнинг 3 даражаси | G\'azabning 3 darajasi',
    duration: '4:33',
    videoId: 'iuTdsXZEmE4',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r054',
    categoryId: 'ramazon',
    title: '53. Ноўрин ғазаб қоралангандир | Noo\'rin g\'azab qoralangandir',
    duration: '4:30',
    videoId: '3df2O2nxjl0',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r055',
    categoryId: 'ramazon',
    title: '54. Ғазаб қилма | G\'azab qilma',
    duration: '3:16',
    videoId: 'Qakx-ZKi6dg',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r056',
    categoryId: 'ramazon',
    title: '55. Ғазаб ҳақидаги оятлар | G\'azab haqidagi oyatlar',
    duration: '3:45',
    videoId: 'lEE7ighJ-8Y',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r057',
    categoryId: 'ramazon',
    title: '57. Ғазабнинг сабаблари | G\'azabning sabablari',
    duration: '6:32',
    videoId: 'nHKMvPTruWw',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r058',
    categoryId: 'ramazon',
    title: '58. Банда ўзининг кимлигини унутмасин | Banda o\'zining kimligini unutmasin',
    duration: '7:36',
    videoId: 'WayPZKPunj4',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r059',
    categoryId: 'ramazon',
    title: '59. Ҳавои нафс нима? | Havoi nafs nima?',
    duration: '2:12',
    videoId: 'XAmIU5bwjts',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r060',
    categoryId: 'ramazon',
    title: '60. Ҳавои нафсга эргашганлан ҳақидаги оят |  Havoi nafsga ergashganlan haqidagi oyat',
    duration: '8:52',
    videoId: 'dOP4hXcSr6Y',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r061',
    categoryId: 'ramazon',
    title: '61. Пайғамбар алайҳиссаломга эргашмаслик   ҳавои нафсга эргашишликдир',
    duration: '4:16',
    videoId: 'bF-BGmcdzoM',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r062',
    categoryId: 'ramazon',
    title: '62. Қиёмат соати келувчидир | Qiyomat soati keluvchidir',
    duration: '6:17',
    videoId: 'O6erYmTI8qc',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r063',
    categoryId: 'ramazon',
    title: '63. Оқил одам ким? | Oqil odam kim?',
    duration: '2:37',
    videoId: 'nXKoNIwjcOI',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r064',
    categoryId: 'ramazon',
    title: '64. Ҳавои нафсни жиловлаш ҳақида | Havoi nafsni jilovlash haqida',
    duration: '6:18',
    videoId: '4zY-OGa6o_4',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r065',
    categoryId: 'ramazon',
    title: '64. Ҳавои нафсни жиловлаш ҳақида | Havoi nafsni jilovlash haqida',
    duration: '6:18',
    videoId: 'NZvjXxe8_Qc',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r066',
    categoryId: 'ramazon',
    title: '65. Руҳий тарбиянинг аҳамияти | Ruhiy tarbiyaning ahamiyati',
    duration: '5:38',
    videoId: '2i0HVcA0KiI',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r067',
    categoryId: 'ramazon',
    title: '66. Ҳол ва мақом | Hol va maqom',
    duration: '3:58',
    videoId: '0PRvHttAwq8',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r068',
    categoryId: 'ramazon',
    title: '67. Тавҳид ҳақида | Tavhid haqida',
    duration: '7:09',
    videoId: 'fNAqC2o2rzU',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r069',
    categoryId: 'ramazon',
    title: '68. Тавҳиднинг фазли | Tavhidning fazli',
    duration: '2:20',
    videoId: 'K55zsS5bPjs',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r070',
    categoryId: 'ramazon',
    title: '69. Тавҳид асосидаги ибодат | Tavhid asosidagi ibodat',
    duration: '15:13',
    videoId: 'PyJSdcholNw',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r071',
    categoryId: 'ramazon',
    title: '70. Ибодат тушунчаси | Ibodat tushunchasi',
    duration: '2:54',
    videoId: 'nZ5IR59Qz4E',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r072',
    categoryId: 'ramazon',
    title: '71. Бандаликдан юксак мақом йўқ | Bandalikdan yuksak maqom yo\'q',
    duration: '11:03',
    videoId: 'iGMbpozxawE',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r073',
    categoryId: 'ramazon',
    title: '72. Ихлос ҳақида | Ixlos haqida',
    duration: '5:10',
    videoId: 'V0i1NGzVcbA',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r074',
    categoryId: 'ramazon',
    title: '73. Ихлос - Аллоҳнинг сири | Ixlos - Allohning siri',
    duration: '4:11',
    videoId: 'n8PiRzi762o',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r075',
    categoryId: 'ramazon',
    title: '74. Ихлос ҳақидаги ҳадислар | Ixlos haqidagi hadislar',
    duration: '6:23',
    videoId: '4qmBWRD-FLQ',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r076',
    categoryId: 'ramazon',
    title: '75. 40 кун ихлос қилган киши | 40 kun ixlos qilgan kishi',
    duration: '1:39',
    videoId: '-PeE46Uu_-Y',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r077',
    categoryId: 'ramazon',
    title: '76. Ихлоснинг даражалари | Ихлоснинг даражалари',
    duration: '6:56',
    videoId: 't3uBKtXZfyk',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r078',
    categoryId: 'ramazon',
    title: '77. Ихлосни тўсувчи нарсалар | Ixlosni to\'suvchi narsalar',
    duration: '9:14',
    videoId: 'XxyWTKKnO6g',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r079',
    categoryId: 'ramazon',
    title: '78. Сидқ ҳақида | Sidq haqida',
    duration: '4:27',
    videoId: 'yuo4eGYmbkM',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r080',
    categoryId: 'ramazon',
    title: '79. Сидқ ва ихлоснинг фарқи | Sidq va ixlosning farqi',
    duration: '1:21',
    videoId: 'Zjf5WxPiIjs',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r081',
    categoryId: 'ramazon',
    title: '80. Сидқ ҳақидаги оятлар | Sidq haqidagi oyatlar',
    duration: '8:51',
    videoId: 'ruyc0xXZ1cQ',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r082',
    categoryId: 'ramazon',
    title: '81. Муҳаммад алайҳиссалом содиқ эдилар | Muhammad alayhissalom sodiq edilar',
    duration: '4:47',
    videoId: 'z--d7z0dq8Y',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r083',
    categoryId: 'ramazon',
    title: '82. Содиқлик нажотдир | Sodiqlik najotdir',
    duration: '5:50',
    videoId: 'ubmMSYSGhOo',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r084',
    categoryId: 'ramazon',
    title: '83. Содиқликнинг турлари | Sodiqlikning turlari',
    duration: '6:52',
    videoId: 'syjUv9NTaZ4',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r085',
    categoryId: 'ramazon',
    title: '84. Содиқ бўлиш - буюк бахт | Sodiq bo\'lish - buyuk baxt',
    duration: '4:54',
    videoId: '_wGOGaADcLM',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r086',
    categoryId: 'ramazon',
    title: '85. Зуҳд ҳақида | Zuhd haqida',
    duration: '3:55',
    videoId: 'pzMZdCNqRDI',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r087',
    categoryId: 'ramazon',
    title: '86. Зуҳд ҳақидаги оятлар | Zuhd haqidagi oyatlar',
    duration: '2:50',
    videoId: 'yQ8RmjgImjU',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r088',
    categoryId: 'ramazon',
    title: '87. Зуҳд ҳақидаги ҳадислар | Zuhd haqidagi hadislar',
    duration: '7:59',
    videoId: 'Ysy-O-XBf50',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r089',
    categoryId: 'ramazon',
    title: '89. Зоҳидларнинг имоми | Zohidlarning imomi',
    duration: '1:43',
    videoId: 'GpofOlP2OrY',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r090',
    categoryId: 'ramazon',
    title: '90. Ҳазрати Абу Бакрнинг зуҳдлари | Hazrati Abu Bakrning zuhdlari',
    duration: '0:52',
    videoId: 'iB5gOigGILA',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r091',
    categoryId: 'ramazon',
    title: '91. Ҳазрати Умарнинг зуҳдлари | Hazrati Umarning zuhdlari',
    duration: '5:28',
    videoId: 'dpKXKEuB8jo',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r092',
    categoryId: 'ramazon',
    title: '92. Ҳазрати Алийнинг зуҳдлари | Hazrati Aliyning zuhdlari',
    duration: '1:16',
    videoId: 'R7JABOlbciU',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r093',
    categoryId: 'ramazon',
    title: '93. Зуҳд таркидунёчилик эмас | Zuhd tarkidunyochilik emas',
    duration: '5:36',
    videoId: 'u1cXQh6PC28',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r094',
    categoryId: 'ramazon',
    title: '94. Абдуллоҳ ибн Муборакнинг зуҳдлари | Abdulloh ibn Muborakning zuhdlari',
    duration: '2:07',
    videoId: 'bpTB8G3nOGI',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r095',
    categoryId: 'ramazon',
    title: '95. Дунёни қалбингдан суғуриб ол! | Dunyoni qalbingdan sug\'urib ol!',
    duration: '1:47',
    videoId: 'YvSYouzrOWA',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r096',
    categoryId: 'ramazon',
    title: '96. Балиқнинг муҳаббати ҳақидаги қисса | Baliqning muhabbati haqidagi qissa',
    duration: '4:37',
    videoId: 'lSY4Iw4u87c',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r097',
    categoryId: 'ramazon',
    title: '88. Зуҳднинг турлари |  Zuhdning turlari',
    duration: '3:55',
    videoId: 'gYqtFkwWpRQ',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r098',
    categoryId: 'ramazon',
    title: '97. Таваккул ҳақида | Tavakkul haqida',
    duration: '13:19',
    videoId: 'pMNdRmJQNI8',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r099',
    categoryId: 'ramazon',
    title: '98. Таваккул ҳақидаги оятлар | Tavakkul haqidagi oyatlar',
    duration: '3:29',
    videoId: 'WD8Wwpw0Xi8',
    xp: 15,
    description: 'Ramazon darsi.',
  },
  {
    id: 'r100',
    categoryId: 'ramazon',
    title: '99. Таваккул ҳақидаги ҳадислар | Tavakkul haqidagi hadislar',
    duration: '5:06',
    videoId: 'BmuKPaatM_A',
    xp: 15,
    description: 'Ramazon darsi.',
  },

  // === RUHIY TARBIYA ===
  {
    id: 'rh001',
    categoryId: 'ruhiy',
    title: '2. Husni xulq (Ruhiy tarbiya)',
    duration: '31:08',
    videoId: 'Ko1L5M5Tw_s',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh002',
    categoryId: 'ruhiy',
    title: '3. Ilm (Ruhiy tarbiya)',
    duration: '23:38',
    videoId: '-GfC8GppokE',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh003',
    categoryId: 'ruhiy',
    title: '4. Qalbni tozalash (Ruhiy tarbiya)',
    duration: '34:12',
    videoId: 'q3XrDfz-Rvk',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh004',
    categoryId: 'ruhiy',
    title: '5. Namoz (Ruhiy tarbiya)',
    duration: '50:02',
    videoId: '0W8z_aih42o',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh005',
    categoryId: 'ruhiy',
    title: '6. Zakot (Ruhiy tarbiya)',
    duration: '58:09',
    videoId: 'xu8_o70035A',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh006',
    categoryId: 'ruhiy',
    title: '7. Roʼza (Ruhiy tarbiya)',
    duration: '53:11',
    videoId: 'BfcJFKQll8g',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh007',
    categoryId: 'ruhiy',
    title: '8. Haj (Ruhiy tarbiya)',
    duration: '51:47',
    videoId: '4nsCipaXpIs',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh008',
    categoryId: 'ruhiy',
    title: '9. Qurʼon tilovati (Ruhiy tarbiya)',
    duration: '--:--',
    videoId: 'oSptddXDe-s',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh009',
    categoryId: 'ruhiy',
    title: '10. Zikr (Ruhiy tarbiya)',
    duration: '49:42',
    videoId: 'M7AlUACRQy8',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh010',
    categoryId: 'ruhiy',
    title: '11. Kun tartibi (Ruhiy tarbiya)',
    duration: '52:01',
    videoId: '97Wqii7Bbt8',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh011',
    categoryId: 'ruhiy',
    title: '12. Kun tartibi 2-qism (Ruhiy tarbiya)',
    duration: '46:44',
    videoId: 'YT5QQcP14pg',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh012',
    categoryId: 'ruhiy',
    title: '13. Tafakkur (Ruhiy tarbiya)',
    duration: '49:13',
    videoId: 'cTTyiodPw5U',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh013',
    categoryId: 'ruhiy',
    title: '14. Murobata (Ruhiy tarbiya)',
    duration: '30:15',
    videoId: '1XQjL8BPny4',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh014',
    categoryId: 'ruhiy',
    title: '15. Nafs pokligi (Ruhiy tarbiya)',
    duration: '47:29',
    videoId: 'kuVWpoJWzP0',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh015',
    categoryId: 'ruhiy',
    title: '16. Husni xulq (Ruhiy tarbiya)',
    duration: '47:04',
    videoId: 'if0PjpLS3Ss',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh016',
    categoryId: 'ruhiy',
    title: '17. Husni xulq 2-qism (Ruhiy tarbiya)',
    duration: '51:03',
    videoId: 'MfD-vn65VqE',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh017',
    categoryId: 'ruhiy',
    title: '18. Til ofatlari (Ruhiy tarbiya)',
    duration: '43:19',
    videoId: 'bZjwgTPcJlg',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh018',
    categoryId: 'ruhiy',
    title: '19. Yolgʼon (Ruhiy tarbiya)',
    duration: '51:24',
    videoId: 'fnZOYps86FQ',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh019',
    categoryId: 'ruhiy',
    title: '20. Gʼiybat  (Ruhiy tarbiya)',
    duration: '41:25',
    videoId: 'y9Gw9KTGsO0',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh020',
    categoryId: 'ruhiy',
    title: '22. Maddohlik (Ruhiy tarbiya)',
    duration: '--:--',
    videoId: 'M5d8ImJ79qg',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh021',
    categoryId: 'ruhiy',
    title: '23.Kufr (Ruhiy tarbiya)',
    duration: '40:11',
    videoId: 'yU_v20qUHS8',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh022',
    categoryId: 'ruhiy',
    title: '24. Shirk (Ruhiy tarbiya)',
    duration: '41:47',
    videoId: 'yDngk6aj3Xk',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh023',
    categoryId: 'ruhiy',
    title: '25. Fosiqlik (Ruhiy tarbiya)',
    duration: '42:12',
    videoId: '85aGBzcxwdk',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh024',
    categoryId: 'ruhiy',
    title: '27. Riyo (Ruhiy tarbiya)',
    duration: '46:35',
    videoId: 'hlVdK9WRNuo',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh025',
    categoryId: 'ruhiy',
    title: '28. Hasad (Ruhiy tarbiya)',
    duration: '--:--',
    videoId: 'WNXugcfCrO0',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh026',
    categoryId: 'ruhiy',
    title: '29. Kibr (Ruhiy tarbiya)',
    duration: '40:30',
    videoId: 'IhH8dnSogzM',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh027',
    categoryId: 'ruhiy',
    title: '30. Manmanlik (Ruhiy tarbiya)',
    duration: '30:53',
    videoId: 'I1qC02O89Z8',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh028',
    categoryId: 'ruhiy',
    title: '31. Baxillik (Ruhiy tarbiya)',
    duration: '32:26',
    videoId: '643g8OnMzNI',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh029',
    categoryId: 'ruhiy',
    title: '32. Mol dunyoga munosabat (Ruhiy tarbiya)',
    duration: '44:02',
    videoId: '3iuPIs_Sd_U',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh030',
    categoryId: 'ruhiy',
    title: '34. Gʼururga ketish (Ruhiy tarbiya)',
    duration: '50:16',
    videoId: '_GQtbN3kVX4',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh031',
    categoryId: 'ruhiy',
    title: '33. Mol-dunyoga hirs qoʼyish (Ruhiy tarbiya)',
    duration: '34:12',
    videoId: 'Z6BQ76akiG0',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh032',
    categoryId: 'ruhiy',
    title: '35. Nooʼrin gʼazab  (Ruhiy tarbiya)',
    duration: '40:09',
    videoId: 'nWVNdZ6hG70',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh033',
    categoryId: 'ruhiy',
    title: '36. Havoi nafs (Ruhiy tarbiya)',
    duration: '36:16',
    videoId: 'BW0h4XF9onQ',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh034',
    categoryId: 'ruhiy',
    title: '37. Tavhid (Ruhiy tarbiya)',
    duration: '50:12',
    videoId: 'nKTPT2nFjXA',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh035',
    categoryId: 'ruhiy',
    title: '38. Ihlos (Ruhiy tarbiya)',
    duration: '40:45',
    videoId: 'Yb-upYhy08o',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh036',
    categoryId: 'ruhiy',
    title: '39. Sidq (Ruhiy tarbiya)',
    duration: '41:26',
    videoId: 'DQAF90scyho',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh037',
    categoryId: 'ruhiy',
    title: '40. Zuhd (Ruhiy tarbiya)',
    duration: '46:44',
    videoId: 'YBSMVbqgXEM',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh038',
    categoryId: 'ruhiy',
    title: '41. Tavakkul (Ruhiy tarbiya)',
    duration: '32:55',
    videoId: 'BcA9RQSwQic',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh039',
    categoryId: 'ruhiy',
    title: '42. Аlloh taoloning muhabbati (Ruhiy tarbiya)',
    duration: '42:09',
    videoId: '6sM4m3-SyF0',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh040',
    categoryId: 'ruhiy',
    title: '43. Xavf  (Ruhiy tarbiya)',
    duration: '36:01',
    videoId: 'dybs-61ZyHk',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh041',
    categoryId: 'ruhiy',
    title: '44. Rajo  (Ruhiy tarbiya)',
    duration: '33:39',
    videoId: 'YqYSoYsizSk',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh042',
    categoryId: 'ruhiy',
    title: '45. Taqvo (Ruhiy tarbiya)',
    duration: '34:59',
    videoId: 'WB65BhUbNLg',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh043',
    categoryId: 'ruhiy',
    title: '46. Shukur (Ruhiy tarbiya)',
    duration: '39:21',
    videoId: 'fBe-6Yx_i9w',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh044',
    categoryId: 'ruhiy',
    title: '47. Sabr. (Ruhiy tarbiya)',
    duration: '51:02',
    videoId: '6XMj9oAnr3c',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh045',
    categoryId: 'ruhiy',
    title: '48. Rizo (Ruhiy tarbiya)',
    duration: '39:07',
    videoId: 'wBl0ZAjdKaQ',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh046',
    categoryId: 'ruhiy',
    title: '49.Muroqaba (Ruhiy tarbiya)',
    duration: '44:25',
    videoId: '1kdBfmwvUYc',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh047',
    categoryId: 'ruhiy',
    title: '50. Tavba (Ruhiy tarbiya)',
    duration: '41:43',
    videoId: 'Ka4nZZEvtSA',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh048',
    categoryId: 'ruhiy',
    title: '51. Iffat (Ruhiy tarbiya)',
    duration: '44:23',
    videoId: 'MVPUHZkTR40',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh049',
    categoryId: 'ruhiy',
    title: '52. Hayo (Ruhiy tarbiya)',
    duration: '46:26',
    videoId: 'Luq7wP2_AA8',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh050',
    categoryId: 'ruhiy',
    title: '53. Varaʼ (Ruhiy tarbiya)',
    duration: '51:52',
    videoId: 'W2jZE0sfcec',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh051',
    categoryId: 'ruhiy',
    title: '55. Taanniy (Ruhiy tarbiya)',
    duration: '33:23',
    videoId: 'g5wxzWdkn9o',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh052',
    categoryId: 'ruhiy',
    title: '56. Tavba (Ruhiy tarbiya)',
    duration: '45:25',
    videoId: 'f6kQjAZBwWk',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh053',
    categoryId: 'ruhiy',
    title: '57. Tabayyun (Ruhiy tarbiya)',
    duration: '41:59',
    videoId: 'uMmOaYqZDS4',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh054',
    categoryId: 'ruhiy',
    title: '58. Solihlik (Ruhiy tarbiya)',
    duration: '30:16',
    videoId: 'D3P3HhVMEv0',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh055',
    categoryId: 'ruhiy',
    title: '59. Аllohning xulqlari bilan xulqlanish (Ruhiy tarbiya)',
    duration: '23:31',
    videoId: 'rFpUpdPLOy4',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh056',
    categoryId: 'ruhiy',
    title: '60. Аllohning Rohim sifati  (Ruhiy tarbiya)',
    duration: '35:55',
    videoId: 'LpOy2Zyaf5Y',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh057',
    categoryId: 'ruhiy',
    title: '61. Аllohning Salom ismi (Ruhiy tarbiya)',
    duration: '33:16',
    videoId: 'riw22OBf07E',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh058',
    categoryId: 'ruhiy',
    title: '62. Аllohning Аl Аziz ismi (Ruhiy tarbiya)',
    duration: '34:22',
    videoId: '18FI_nvGdkA',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh059',
    categoryId: 'ruhiy',
    title: '63. Аllohning Аl Аdl ismi (Ruhiy tarbiya)',
    duration: '41:19',
    videoId: 'gug1komTtzM',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh060',
    categoryId: 'ruhiy',
    title: '64. Аllohning Halim sifati (Ruhiy tarbiya)',
    duration: '34:24',
    videoId: 'dEFmE1Kd_7M',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh061',
    categoryId: 'ruhiy',
    title: '65. Аllohning Karim ismi (Ruhiy tarbiya)',
    duration: '34:42',
    videoId: 'vmgM_s7txz0',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh062',
    categoryId: 'ruhiy',
    title: '66. Аllohning Аl Hakiym ismi  (Ruhiy tarbiya)',
    duration: '35:38',
    videoId: 'ssvmd5bpSVU',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh063',
    categoryId: 'ruhiy',
    title: '67. Аllohning Barr ismi  (Ruhiy tarbiya)',
    duration: '44:46',
    videoId: '7gChtigYXSM',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh064',
    categoryId: 'ruhiy',
    title: '68. Аllohning Аfuvv ismi  (Ruhiy tarbiya)',
    duration: '31:47',
    videoId: 'gyKVB5FQlf0',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh065',
    categoryId: 'ruhiy',
    title: '69. Rasululloh alayhissalomning baʼzi ahloqlari (Ruhiy tarbiya)',
    duration: '40:30',
    videoId: 'Pxvo5agwBjU',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh066',
    categoryId: 'ruhiy',
    title: '70. Rasululloh alayhissalomning xalqlari (Ruhiy tarbiya)',
    duration: '35:34',
    videoId: 'RPqDXYtki-I',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh067',
    categoryId: 'ruhiy',
    title: '71. Rasululloh alayhissalomning ahloqlari (Ruhiy tarbiya)',
    duration: '35:35',
    videoId: 'HWg8EDfRhO0',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh068',
    categoryId: 'ruhiy',
    title: '73. Nabiy alayhissalomning taomdagi ahloqlari (Ruhiy tarbiya)',
    duration: '30:44',
    videoId: 'i4buBbhJev8',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh069',
    categoryId: 'ruhiy',
    title: '75. Bandaning bandadagi haqqi 1-qism (Ruhiy tarbiya)',
    duration: '38:15',
    videoId: '88iyAYJr6CQ',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh070',
    categoryId: 'ruhiy',
    title: '76. Bandaning bandadagi haqqi 2-qism (Ruhiy tarbiya)',
    duration: '43:31',
    videoId: 'kVQAfBGfvYU',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh071',
    categoryId: 'ruhiy',
    title: '77. Bandaning bandadagi haqqi 3-qism (Ruhiy tarbiya)',
    duration: '30:23',
    videoId: 'Tm4vLgXftck',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh072',
    categoryId: 'ruhiy',
    title: '78. Ota onaning haqqi (Ruhiy tarbiya)',
    duration: '41:16',
    videoId: 'RRBOTYyNXKA',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh073',
    categoryId: 'ruhiy',
    title: '79. Farzandning ota onadagi haqlari (Ruhiy tarbiya)',
    duration: '35:11',
    videoId: 'ehJ_B-2szSg',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh074',
    categoryId: 'ruhiy',
    title: '80. Qarindoshlik haqlari (Ruhiy tarbiya)',
    duration: '28:04',
    videoId: 'pJhxMSN3Zak',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh075',
    categoryId: 'ruhiy',
    title: '81. Er xotinlik huquqlari 1-qism (Ruhiy tarbiya)',
    duration: '37:14',
    videoId: '_hJh9hw5-fk',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh076',
    categoryId: 'ruhiy',
    title: '84. Muomala odoblari (Ruhiy tarbiya)',
    duration: '33:40',
    videoId: 'Fh5AGY9Xq6Q',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh077',
    categoryId: 'ruhiy',
    title: '85. Ish haqqi (Ruhiy tarbiya)',
    duration: '15:42',
    videoId: 'EOBYuOZJ5vw',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh078',
    categoryId: 'ruhiy',
    title: '86. Jamodot olami haqlari (Ruhiy tarbiya)',
    duration: '13:39',
    videoId: 'weksiDSOHZk',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh079',
    categoryId: 'ruhiy',
    title: '87. Hayvonot olami bilan muomala (Ruhiy tarbiya)',
    duration: '36:47',
    videoId: 'MFcclFDe1C8',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
  {
    id: 'rh080',
    categoryId: 'ruhiy',
    title: '88. Nabodot olami bilan muomala  (Ruhiy tarbiya)',
    duration: '47:02',
    videoId: 'zMcVTHtxuKY',
    xp: 15,
    description: 'Ruhiy tarbiya darsi.',
  },
];

export const VIDEO_XP_BONUS = {
  daily3: { count: 3, xp: 25, label: 'Kunlik 3 ta video' },
  category: { xp: 50, label: 'Kategoriyani tugatish' },
  allVideos: { xp: 200, label: "Barcha darsliklarni ko'rish" },
};
